language: go
go:
  - 1.8
addons:
  apt:
    packages:
    - tmux
cache:
  directories:
    - vendor
before_install:
  # install go dependencies
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/tools/cmd/cover

  # install fzf
  - curl -L https://github.com/junegunn/fzf-bin/releases/download/0.16.11/fzf-0.16.11-linux_amd64.tgz | tar -C ~ -xf
  - export PATH=$PATH:~
install:
  - dep ensure
script: go test -v -cover -bench=. $(go list ./... | grep -v /vendor/)
