language: go
go:
  - 1.12
addons:
  apt:
    packages:
    - tmux
env:
  global:
    - FZF_VERSION=0.16.11
before_install:
  # install go dependencies
  - go get -u golang.org/x/tools/cmd/cover

  # install fzf
  - curl -L https://github.com/junegunn/fzf-bin/releases/download/$FZF_VERSION/fzf-$FZF_VERSION-linux_amd64.tgz | tar -C ~ -xz
  - export PATH=$PATH:~
install:
  - go mod tidy
script: make ci
