language: go
go:
  - 1.8
cache:
  directories:
    - vendor
    - $HOME/.glide
before_install:
  # Install Glide
  - curl https://glide.sh/get | bash
before_script:
  - glide install
  - go get -u golang.org/x/tools/cmd/cover
script: go test $(glide nv)
