language: nix
addons:
  apt:
    packages:
    - tmux
env:
  global:
    - FZF_VERSION=0.20.0
before_install:
  # install fzf
  - curl -L https://github.com/junegunn/fzf-bin/releases/download/$FZF_VERSION/fzf-$FZF_VERSION-linux_amd64.tgz | tar -C ~ -xz
  - export PATH=$PATH:~
script:
  - nix-shell --run 'go test -v -race -cover -bench=. ./...'
  - >
    if [[ "$( git --no-pager status --untracked-files=no --short | wc -l )" -gt 0 ]]; then
      echo ">>> Changes were detected after we ran the tests, this should not happen!"
      echo; echo; echo;
      git --no-pager diff
      exit 1
    fi
  - nix-shell --run 'go run main.go gen-doc markdown --path ./doc'
  - >
    if [[ "$( git --no-pager status --untracked-files=no --short | wc -l )" -gt 0 ]]; then
    echo ">>> Changes detected to the documentation, re-generate with: go run main.go gen-doc markdown --path ./doc"
      echo; echo; echo;
      git --no-pager diff
      exit 1
    fi
