language: go
go:
  - 1.8
addons:
  apt:
    packages:
    - tmux
cache:
  directories:
    - vendor
env:
  global:
    - FZF_VERSION=0.16.11
before_install:
  # install go dependencies
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/tools/cmd/cover

  # install fzf
  - curl -L https://github.com/junegunn/fzf-bin/releases/download/$FZF_VERSION/fzf-$FZF_VERSION-linux_amd64.tgz | tar -C ~ -xz
  - export PATH=$PATH:~
install:
  - dep ensure
script: make ci
