language: go
go:
  - 1.8
cache:
  directories:
    - vendor
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/tools/cmd/cover
install:
  - dep ensure
script: go test -v -cover -bench=. $(go list ./... | grep -v /vendor/)
