// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swm/plugin/v1/common.proto

package pluginv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CapabilityType enumerates the capability surfaces a plugin may provide.
type CapabilityType int32

const (
	CapabilityType_CAPABILITY_TYPE_UNSPECIFIED CapabilityType = 0
	CapabilityType_CAPABILITY_TYPE_SESSION     CapabilityType = 1
	CapabilityType_CAPABILITY_TYPE_VCS         CapabilityType = 2
	CapabilityType_CAPABILITY_TYPE_FORGE       CapabilityType = 3
	CapabilityType_CAPABILITY_TYPE_PICKER      CapabilityType = 4
	CapabilityType_CAPABILITY_TYPE_HOOK        CapabilityType = 5
)

// Enum value maps for CapabilityType.
var (
	CapabilityType_name = map[int32]string{
		0: "CAPABILITY_TYPE_UNSPECIFIED",
		1: "CAPABILITY_TYPE_SESSION",
		2: "CAPABILITY_TYPE_VCS",
		3: "CAPABILITY_TYPE_FORGE",
		4: "CAPABILITY_TYPE_PICKER",
		5: "CAPABILITY_TYPE_HOOK",
	}
	CapabilityType_value = map[string]int32{
		"CAPABILITY_TYPE_UNSPECIFIED": 0,
		"CAPABILITY_TYPE_SESSION":     1,
		"CAPABILITY_TYPE_VCS":         2,
		"CAPABILITY_TYPE_FORGE":       3,
		"CAPABILITY_TYPE_PICKER":      4,
		"CAPABILITY_TYPE_HOOK":        5,
	}
)

func (x CapabilityType) Enum() *CapabilityType {
	p := new(CapabilityType)
	*p = x
	return p
}

func (x CapabilityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityType) Descriptor() protoreflect.EnumDescriptor {
	return file_swm_plugin_v1_common_proto_enumTypes[0].Descriptor()
}

func (CapabilityType) Type() protoreflect.EnumType {
	return &file_swm_plugin_v1_common_proto_enumTypes[0]
}

func (x CapabilityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityType.Descriptor instead.
func (CapabilityType) EnumDescriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

// Empty is used for RPCs with no request or response fields.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

// BoolValue wraps a bool for RPCs that return a single boolean.
type BoolValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolValue) Reset() {
	*x = BoolValue{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolValue) ProtoMessage() {}

func (x *BoolValue) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolValue.ProtoReflect.Descriptor instead.
func (*BoolValue) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *BoolValue) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

// PathResponse wraps a filesystem path string.
type PathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PathResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ProjectID uniquely identifies a source repository by its URL-derived tuple.
// The host composes on-disk paths from this tuple; plugins never choose layout.
type ProjectID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Segments      []string               `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectID) Reset() {
	*x = ProjectID{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectID) ProtoMessage() {}

func (x *ProjectID) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectID.ProtoReflect.Descriptor instead.
func (*ProjectID) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectID) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProjectID) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

// Capability describes a single capability surface.
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CapabilityType         `protobuf:"varint,1,opt,name=type,proto3,enum=swm.plugin.v1.CapabilityType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Capability) GetType() CapabilityType {
	if x != nil {
		return x.Type
	}
	return CapabilityType_CAPABILITY_TYPE_UNSPECIFIED
}

// CapabilityDep declares a required dependency on another capability.
type CapabilityDep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    CapabilityType         `protobuf:"varint,1,opt,name=capability,proto3,enum=swm.plugin.v1.CapabilityType" json:"capability,omitempty"`
	MinVersion    string                 `protobuf:"bytes,2,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityDep) Reset() {
	*x = CapabilityDep{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDep) ProtoMessage() {}

func (x *CapabilityDep) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDep.ProtoReflect.Descriptor instead.
func (*CapabilityDep) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilityDep) GetCapability() CapabilityType {
	if x != nil {
		return x.Capability
	}
	return CapabilityType_CAPABILITY_TYPE_UNSPECIFIED
}

func (x *CapabilityDep) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

// PluginInfo is returned by every plugin's Info RPC and describes itself.
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Provides      []*Capability          `protobuf:"bytes,3,rep,name=provides,proto3" json:"provides,omitempty"`
	Requires      []*CapabilityDep       `protobuf:"bytes,4,rep,name=requires,proto3" json:"requires,omitempty"`
	Optional      []string               `protobuf:"bytes,5,rep,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetProvides() []*Capability {
	if x != nil {
		return x.Provides
	}
	return nil
}

func (x *PluginInfo) GetRequires() []*CapabilityDep {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *PluginInfo) GetOptional() []string {
	if x != nil {
		return x.Optional
	}
	return nil
}

// Project records a source repository attached to a story.
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Segments      []string               `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	Vcs           string                 `protobuf:"bytes,3,opt,name=vcs,proto3" json:"vcs,omitempty"`
	AttachedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=attached_at,json=attachedAt,proto3" json:"attached_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *Project) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Project) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Project) GetVcs() string {
	if x != nil {
		return x.Vcs
	}
	return ""
}

func (x *Project) GetAttachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttachedAt
	}
	return nil
}

// Story represents a unit of work with attached projects.
type Story struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BranchName    string                 `protobuf:"bytes,2,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Vcs           string                 `protobuf:"bytes,4,opt,name=vcs,proto3" json:"vcs,omitempty"`
	Projects      []*Project             `protobuf:"bytes,5,rep,name=projects,proto3" json:"projects,omitempty"`
	Metadata      map[string][]byte      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Story) Reset() {
	*x = Story{}
	mi := &file_swm_plugin_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *Story) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Story) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *Story) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Story) GetVcs() string {
	if x != nil {
		return x.Vcs
	}
	return ""
}

func (x *Story) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Story) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_swm_plugin_v1_common_proto protoreflect.FileDescriptor

const file_swm_plugin_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aswm/plugin/v1/common.proto\x12\rswm.plugin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"!\n" +
	"\tBoolValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"\"\n" +
	"\fPathResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\";\n" +
	"\tProjectID\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\bsegments\x18\x02 \x03(\tR\bsegments\"?\n" +
	"\n" +
	"Capability\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.swm.plugin.v1.CapabilityTypeR\x04type\"o\n" +
	"\rCapabilityDep\x12=\n" +
	"\n" +
	"capability\x18\x01 \x01(\x0e2\x1d.swm.plugin.v1.CapabilityTypeR\n" +
	"capability\x12\x1f\n" +
	"\vmin_version\x18\x02 \x01(\tR\n" +
	"minVersion\"\xc7\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x125\n" +
	"\bprovides\x18\x03 \x03(\v2\x19.swm.plugin.v1.CapabilityR\bprovides\x128\n" +
	"\brequires\x18\x04 \x03(\v2\x1c.swm.plugin.v1.CapabilityDepR\brequires\x12\x1a\n" +
	"\boptional\x18\x05 \x03(\tR\boptional\"\x88\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\bsegments\x18\x02 \x03(\tR\bsegments\x12\x10\n" +
	"\x03vcs\x18\x03 \x01(\tR\x03vcs\x12;\n" +
	"\vattached_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"attachedAt\"\xba\x02\n" +
	"\x05Story\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vbranch_name\x18\x02 \x01(\tR\n" +
	"branchName\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x10\n" +
	"\x03vcs\x18\x04 \x01(\tR\x03vcs\x122\n" +
	"\bprojects\x18\x05 \x03(\v2\x16.swm.plugin.v1.ProjectR\bprojects\x12>\n" +
	"\bmetadata\x18\x06 \x03(\v2\".swm.plugin.v1.Story.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01*\xb8\x01\n" +
	"\x0eCapabilityType\x12\x1f\n" +
	"\x1bCAPABILITY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CAPABILITY_TYPE_SESSION\x10\x01\x12\x17\n" +
	"\x13CAPABILITY_TYPE_VCS\x10\x02\x12\x19\n" +
	"\x15CAPABILITY_TYPE_FORGE\x10\x03\x12\x1a\n" +
	"\x16CAPABILITY_TYPE_PICKER\x10\x04\x12\x18\n" +
	"\x14CAPABILITY_TYPE_HOOK\x10\x05B6Z4github.com/kalbasit/swm/proto/swm/plugin/v1;pluginv1b\x06proto3"

var (
	file_swm_plugin_v1_common_proto_rawDescOnce sync.Once
	file_swm_plugin_v1_common_proto_rawDescData []byte
)

func file_swm_plugin_v1_common_proto_rawDescGZIP() []byte {
	file_swm_plugin_v1_common_proto_rawDescOnce.Do(func() {
		file_swm_plugin_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_common_proto_rawDesc), len(file_swm_plugin_v1_common_proto_rawDesc)))
	})
	return file_swm_plugin_v1_common_proto_rawDescData
}

var (
	file_swm_plugin_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_swm_plugin_v1_common_proto_msgTypes  = make([]protoimpl.MessageInfo, 10)
	file_swm_plugin_v1_common_proto_goTypes   = []any{
		CapabilityType(0),             // 0: swm.plugin.v1.CapabilityType
		(*Empty)(nil),                 // 1: swm.plugin.v1.Empty
		(*BoolValue)(nil),             // 2: swm.plugin.v1.BoolValue
		(*PathResponse)(nil),          // 3: swm.plugin.v1.PathResponse
		(*ProjectID)(nil),             // 4: swm.plugin.v1.ProjectID
		(*Capability)(nil),            // 5: swm.plugin.v1.Capability
		(*CapabilityDep)(nil),         // 6: swm.plugin.v1.CapabilityDep
		(*PluginInfo)(nil),            // 7: swm.plugin.v1.PluginInfo
		(*Project)(nil),               // 8: swm.plugin.v1.Project
		(*Story)(nil),                 // 9: swm.plugin.v1.Story
		nil,                           // 10: swm.plugin.v1.Story.MetadataEntry
		(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	}
)
var file_swm_plugin_v1_common_proto_depIdxs = []int32{
	0,  // 0: swm.plugin.v1.Capability.type:type_name -> swm.plugin.v1.CapabilityType
	0,  // 1: swm.plugin.v1.CapabilityDep.capability:type_name -> swm.plugin.v1.CapabilityType
	5,  // 2: swm.plugin.v1.PluginInfo.provides:type_name -> swm.plugin.v1.Capability
	6,  // 3: swm.plugin.v1.PluginInfo.requires:type_name -> swm.plugin.v1.CapabilityDep
	11, // 4: swm.plugin.v1.Project.attached_at:type_name -> google.protobuf.Timestamp
	11, // 5: swm.plugin.v1.Story.created_at:type_name -> google.protobuf.Timestamp
	8,  // 6: swm.plugin.v1.Story.projects:type_name -> swm.plugin.v1.Project
	10, // 7: swm.plugin.v1.Story.metadata:type_name -> swm.plugin.v1.Story.MetadataEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_swm_plugin_v1_common_proto_init() }
func file_swm_plugin_v1_common_proto_init() {
	if File_swm_plugin_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_common_proto_rawDesc), len(file_swm_plugin_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swm_plugin_v1_common_proto_goTypes,
		DependencyIndexes: file_swm_plugin_v1_common_proto_depIdxs,
		EnumInfos:         file_swm_plugin_v1_common_proto_enumTypes,
		MessageInfos:      file_swm_plugin_v1_common_proto_msgTypes,
	}.Build()
	File_swm_plugin_v1_common_proto = out.File
	file_swm_plugin_v1_common_proto_goTypes = nil
	file_swm_plugin_v1_common_proto_depIdxs = nil
}
