// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: swm/plugin/v1/forge.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Forge_Info_FullMethodName              = "/swm.plugin.v1.Forge/Info"
	Forge_ListPullRequests_FullMethodName  = "/swm.plugin.v1.Forge/ListPullRequests"
	Forge_CreatePullRequest_FullMethodName = "/swm.plugin.v1.Forge/CreatePullRequest"
	Forge_GetPullRequest_FullMethodName    = "/swm.plugin.v1.Forge/GetPullRequest"
)

// ForgeClient is the client API for Forge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Forge is implemented by code-host plugins (e.g. forge-github).
type ForgeClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ForgeInfo, error)
	ListPullRequests(ctx context.Context, in *ListPRsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullRequest], error)
	CreatePullRequest(ctx context.Context, in *CreatePRRequest, opts ...grpc.CallOption) (*PullRequest, error)
	GetPullRequest(ctx context.Context, in *GetPRRequest, opts ...grpc.CallOption) (*PullRequest, error)
}

type forgeClient struct {
	cc grpc.ClientConnInterface
}

func NewForgeClient(cc grpc.ClientConnInterface) ForgeClient {
	return &forgeClient{cc}
}

func (c *forgeClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ForgeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgeInfo)
	err := c.cc.Invoke(ctx, Forge_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) ListPullRequests(ctx context.Context, in *ListPRsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Forge_ServiceDesc.Streams[0], Forge_ListPullRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListPRsRequest, PullRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Forge_ListPullRequestsClient = grpc.ServerStreamingClient[PullRequest]

func (c *forgeClient) CreatePullRequest(ctx context.Context, in *CreatePRRequest, opts ...grpc.CallOption) (*PullRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullRequest)
	err := c.cc.Invoke(ctx, Forge_CreatePullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) GetPullRequest(ctx context.Context, in *GetPRRequest, opts ...grpc.CallOption) (*PullRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullRequest)
	err := c.cc.Invoke(ctx, Forge_GetPullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForgeServer is the server API for Forge service.
// All implementations should embed UnimplementedForgeServer
// for forward compatibility.
//
// Forge is implemented by code-host plugins (e.g. forge-github).
type ForgeServer interface {
	Info(context.Context, *Empty) (*ForgeInfo, error)
	ListPullRequests(*ListPRsRequest, grpc.ServerStreamingServer[PullRequest]) error
	CreatePullRequest(context.Context, *CreatePRRequest) (*PullRequest, error)
	GetPullRequest(context.Context, *GetPRRequest) (*PullRequest, error)
}

// UnimplementedForgeServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForgeServer struct{}

func (UnimplementedForgeServer) Info(context.Context, *Empty) (*ForgeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedForgeServer) ListPullRequests(*ListPRsRequest, grpc.ServerStreamingServer[PullRequest]) error {
	return status.Error(codes.Unimplemented, "method ListPullRequests not implemented")
}
func (UnimplementedForgeServer) CreatePullRequest(context.Context, *CreatePRRequest) (*PullRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePullRequest not implemented")
}
func (UnimplementedForgeServer) GetPullRequest(context.Context, *GetPRRequest) (*PullRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullRequest not implemented")
}
func (UnimplementedForgeServer) testEmbeddedByValue() {}

// UnsafeForgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForgeServer will
// result in compilation errors.
type UnsafeForgeServer interface {
	mustEmbedUnimplementedForgeServer()
}

func RegisterForgeServer(s grpc.ServiceRegistrar, srv ForgeServer) {
	// If the following call panics, it indicates UnimplementedForgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Forge_ServiceDesc, srv)
}

func _Forge_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_ListPullRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPRsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ForgeServer).ListPullRequests(m, &grpc.GenericServerStream[ListPRsRequest, PullRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Forge_ListPullRequestsServer = grpc.ServerStreamingServer[PullRequest]

func _Forge_CreatePullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).CreatePullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_CreatePullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).CreatePullRequest(ctx, req.(*CreatePRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_GetPullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).GetPullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_GetPullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).GetPullRequest(ctx, req.(*GetPRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Forge_ServiceDesc is the grpc.ServiceDesc for Forge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Forge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swm.plugin.v1.Forge",
	HandlerType: (*ForgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Forge_Info_Handler,
		},
		{
			MethodName: "CreatePullRequest",
			Handler:    _Forge_CreatePullRequest_Handler,
		},
		{
			MethodName: "GetPullRequest",
			Handler:    _Forge_GetPullRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPullRequests",
			Handler:       _Forge_ListPullRequests_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swm/plugin/v1/forge.proto",
}
