// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: swm/plugin/v1/host.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Host_GetConfig_FullMethodName       = "/swm.plugin.v1.Host/GetConfig"
	Host_GetCodeRoot_FullMethodName     = "/swm.plugin.v1.Host/GetCodeRoot"
	Host_ListProjects_FullMethodName    = "/swm.plugin.v1.Host/ListProjects"
	Host_GetCurrentStory_FullMethodName = "/swm.plugin.v1.Host/GetCurrentStory"
	Host_Log_FullMethodName             = "/swm.plugin.v1.Host/Log"
	Host_CallCapability_FullMethodName  = "/swm.plugin.v1.Host/CallCapability"
)

// HostClient is the client API for Host service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Host provides callbacks from a plugin back into the swm host.
// Plugins receive a Host client when launched; they never call each other directly.
type HostClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Config, error)
	GetCodeRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PathResponse, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Project], error)
	GetCurrentStory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Story, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
	CallCapability(ctx context.Context, in *CallCapabilityRequest, opts ...grpc.CallOption) (*CallCapabilityResponse, error)
}

type hostClient struct {
	cc grpc.ClientConnInterface
}

func NewHostClient(cc grpc.ClientConnInterface) HostClient {
	return &hostClient{cc}
}

func (c *hostClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Config)
	err := c.cc.Invoke(ctx, Host_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) GetCodeRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathResponse)
	err := c.cc.Invoke(ctx, Host_GetCodeRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Project], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Host_ServiceDesc.Streams[0], Host_ListProjects_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListProjectsRequest, Project]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_ListProjectsClient = grpc.ServerStreamingClient[Project]

func (c *hostClient) GetCurrentStory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Story, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Story)
	err := c.cc.Invoke(ctx, Host_GetCurrentStory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Host_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) CallCapability(ctx context.Context, in *CallCapabilityRequest, opts ...grpc.CallOption) (*CallCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallCapabilityResponse)
	err := c.cc.Invoke(ctx, Host_CallCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServer is the server API for Host service.
// All implementations should embed UnimplementedHostServer
// for forward compatibility.
//
// Host provides callbacks from a plugin back into the swm host.
// Plugins receive a Host client when launched; they never call each other directly.
type HostServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*Config, error)
	GetCodeRoot(context.Context, *Empty) (*PathResponse, error)
	ListProjects(*ListProjectsRequest, grpc.ServerStreamingServer[Project]) error
	GetCurrentStory(context.Context, *Empty) (*Story, error)
	Log(context.Context, *LogRequest) (*Empty, error)
	CallCapability(context.Context, *CallCapabilityRequest) (*CallCapabilityResponse, error)
}

// UnimplementedHostServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServer struct{}

func (UnimplementedHostServer) GetConfig(context.Context, *GetConfigRequest) (*Config, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedHostServer) GetCodeRoot(context.Context, *Empty) (*PathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCodeRoot not implemented")
}
func (UnimplementedHostServer) ListProjects(*ListProjectsRequest, grpc.ServerStreamingServer[Project]) error {
	return status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedHostServer) GetCurrentStory(context.Context, *Empty) (*Story, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentStory not implemented")
}
func (UnimplementedHostServer) Log(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServer) CallCapability(context.Context, *CallCapabilityRequest) (*CallCapabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallCapability not implemented")
}
func (UnimplementedHostServer) testEmbeddedByValue() {}

// UnsafeHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServer will
// result in compilation errors.
type UnsafeHostServer interface {
	mustEmbedUnimplementedHostServer()
}

func RegisterHostServer(s grpc.ServiceRegistrar, srv HostServer) {
	// If the following call panics, it indicates UnimplementedHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Host_ServiceDesc, srv)
}

func _Host_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_GetCodeRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetCodeRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetCodeRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetCodeRoot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListProjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProjectsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostServer).ListProjects(m, &grpc.GenericServerStream[ListProjectsRequest, Project]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Host_ListProjectsServer = grpc.ServerStreamingServer[Project]

func _Host_GetCurrentStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetCurrentStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetCurrentStory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetCurrentStory(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_CallCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).CallCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_CallCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).CallCapability(ctx, req.(*CallCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Host_ServiceDesc is the grpc.ServiceDesc for Host service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Host_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swm.plugin.v1.Host",
	HandlerType: (*HostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _Host_GetConfig_Handler,
		},
		{
			MethodName: "GetCodeRoot",
			Handler:    _Host_GetCodeRoot_Handler,
		},
		{
			MethodName: "GetCurrentStory",
			Handler:    _Host_GetCurrentStory_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _Host_Log_Handler,
		},
		{
			MethodName: "CallCapability",
			Handler:    _Host_CallCapability_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProjects",
			Handler:       _Host_ListProjects_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swm/plugin/v1/host.proto",
}
