// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swm/plugin/v1/host.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetConfigRequest asks the host for the calling plugin's config block.
type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plugin_name scopes the returned config (e.g. "session-tmux").
	PluginName    string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_swm_plugin_v1_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_host_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

// Config carries raw TOML bytes for a plugin's config namespace.
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toml          []byte                 `protobuf:"bytes,1,opt,name=toml,proto3" json:"toml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_swm_plugin_v1_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_host_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetToml() []byte {
	if x != nil {
		return x.Toml
	}
	return nil
}

// ListProjectsRequest asks the host to enumerate known projects.
type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_swm_plugin_v1_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_host_proto_rawDescGZIP(), []int{2}
}

// LogRequest sends a structured log entry to the host's logger.
type LogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// level is "debug", "info", "warn", or "error".
	Level         string            `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_swm_plugin_v1_host_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_host_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_host_proto_rawDescGZIP(), []int{3}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// CallCapabilityRequest routes a cross-plugin call through the host.
type CallCapabilityRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Capability CapabilityType         `protobuf:"varint,1,opt,name=capability,proto3,enum=swm.plugin.v1.CapabilityType" json:"capability,omitempty"`
	// method is the RPC name (e.g. "CreateWorktree").
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// args_json is the request serialised as JSON.
	ArgsJson      string `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCapabilityRequest) Reset() {
	*x = CallCapabilityRequest{}
	mi := &file_swm_plugin_v1_host_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCapabilityRequest) ProtoMessage() {}

func (x *CallCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_host_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCapabilityRequest.ProtoReflect.Descriptor instead.
func (*CallCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_host_proto_rawDescGZIP(), []int{4}
}

func (x *CallCapabilityRequest) GetCapability() CapabilityType {
	if x != nil {
		return x.Capability
	}
	return CapabilityType_CAPABILITY_TYPE_UNSPECIFIED
}

func (x *CallCapabilityRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallCapabilityRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

// CallCapabilityResponse carries the cross-plugin call's result.
type CallCapabilityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result_json is the response serialised as JSON.
	ResultJson    string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCapabilityResponse) Reset() {
	*x = CallCapabilityResponse{}
	mi := &file_swm_plugin_v1_host_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCapabilityResponse) ProtoMessage() {}

func (x *CallCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_host_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCapabilityResponse.ProtoReflect.Descriptor instead.
func (*CallCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_host_proto_rawDescGZIP(), []int{5}
}

func (x *CallCapabilityResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_swm_plugin_v1_host_proto protoreflect.FileDescriptor

const file_swm_plugin_v1_host_proto_rawDesc = "" +
	"\n" +
	"\x18swm/plugin/v1/host.proto\x12\rswm.plugin.v1\x1a\x1aswm/plugin/v1/common.proto\"3\n" +
	"\x10GetConfigRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\"\x1c\n" +
	"\x06Config\x12\x12\n" +
	"\x04toml\x18\x01 \x01(\fR\x04toml\"\x15\n" +
	"\x13ListProjectsRequest\"\xb6\x01\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x06fields\x18\x03 \x03(\v2%.swm.plugin.v1.LogRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x15CallCapabilityRequest\x12=\n" +
	"\n" +
	"capability\x18\x01 \x01(\x0e2\x1d.swm.plugin.v1.CapabilityTypeR\n" +
	"capability\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\tR\bargsJson\"9\n" +
	"\x16CallCapabilityResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson2\xb1\x03\n" +
	"\x04Host\x12C\n" +
	"\tGetConfig\x12\x1f.swm.plugin.v1.GetConfigRequest\x1a\x15.swm.plugin.v1.Config\x12@\n" +
	"\vGetCodeRoot\x12\x14.swm.plugin.v1.Empty\x1a\x1b.swm.plugin.v1.PathResponse\x12L\n" +
	"\fListProjects\x12\".swm.plugin.v1.ListProjectsRequest\x1a\x16.swm.plugin.v1.Project0\x01\x12=\n" +
	"\x0fGetCurrentStory\x12\x14.swm.plugin.v1.Empty\x1a\x14.swm.plugin.v1.Story\x126\n" +
	"\x03Log\x12\x19.swm.plugin.v1.LogRequest\x1a\x14.swm.plugin.v1.Empty\x12]\n" +
	"\x0eCallCapability\x12$.swm.plugin.v1.CallCapabilityRequest\x1a%.swm.plugin.v1.CallCapabilityResponseB6Z4github.com/kalbasit/swm/proto/swm/plugin/v1;pluginv1b\x06proto3"

var (
	file_swm_plugin_v1_host_proto_rawDescOnce sync.Once
	file_swm_plugin_v1_host_proto_rawDescData []byte
)

func file_swm_plugin_v1_host_proto_rawDescGZIP() []byte {
	file_swm_plugin_v1_host_proto_rawDescOnce.Do(func() {
		file_swm_plugin_v1_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_host_proto_rawDesc), len(file_swm_plugin_v1_host_proto_rawDesc)))
	})
	return file_swm_plugin_v1_host_proto_rawDescData
}

var file_swm_plugin_v1_host_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_swm_plugin_v1_host_proto_goTypes = []any{
	(*GetConfigRequest)(nil),       // 0: swm.plugin.v1.GetConfigRequest
	(*Config)(nil),                 // 1: swm.plugin.v1.Config
	(*ListProjectsRequest)(nil),    // 2: swm.plugin.v1.ListProjectsRequest
	(*LogRequest)(nil),             // 3: swm.plugin.v1.LogRequest
	(*CallCapabilityRequest)(nil),  // 4: swm.plugin.v1.CallCapabilityRequest
	(*CallCapabilityResponse)(nil), // 5: swm.plugin.v1.CallCapabilityResponse
	nil,                            // 6: swm.plugin.v1.LogRequest.FieldsEntry
	(CapabilityType)(0),            // 7: swm.plugin.v1.CapabilityType
	(*Empty)(nil),                  // 8: swm.plugin.v1.Empty
	(*PathResponse)(nil),           // 9: swm.plugin.v1.PathResponse
	(*Project)(nil),                // 10: swm.plugin.v1.Project
	(*Story)(nil),                  // 11: swm.plugin.v1.Story
}
var file_swm_plugin_v1_host_proto_depIdxs = []int32{
	6,  // 0: swm.plugin.v1.LogRequest.fields:type_name -> swm.plugin.v1.LogRequest.FieldsEntry
	7,  // 1: swm.plugin.v1.CallCapabilityRequest.capability:type_name -> swm.plugin.v1.CapabilityType
	0,  // 2: swm.plugin.v1.Host.GetConfig:input_type -> swm.plugin.v1.GetConfigRequest
	8,  // 3: swm.plugin.v1.Host.GetCodeRoot:input_type -> swm.plugin.v1.Empty
	2,  // 4: swm.plugin.v1.Host.ListProjects:input_type -> swm.plugin.v1.ListProjectsRequest
	8,  // 5: swm.plugin.v1.Host.GetCurrentStory:input_type -> swm.plugin.v1.Empty
	3,  // 6: swm.plugin.v1.Host.Log:input_type -> swm.plugin.v1.LogRequest
	4,  // 7: swm.plugin.v1.Host.CallCapability:input_type -> swm.plugin.v1.CallCapabilityRequest
	1,  // 8: swm.plugin.v1.Host.GetConfig:output_type -> swm.plugin.v1.Config
	9,  // 9: swm.plugin.v1.Host.GetCodeRoot:output_type -> swm.plugin.v1.PathResponse
	10, // 10: swm.plugin.v1.Host.ListProjects:output_type -> swm.plugin.v1.Project
	11, // 11: swm.plugin.v1.Host.GetCurrentStory:output_type -> swm.plugin.v1.Story
	8,  // 12: swm.plugin.v1.Host.Log:output_type -> swm.plugin.v1.Empty
	5,  // 13: swm.plugin.v1.Host.CallCapability:output_type -> swm.plugin.v1.CallCapabilityResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_swm_plugin_v1_host_proto_init() }
func file_swm_plugin_v1_host_proto_init() {
	if File_swm_plugin_v1_host_proto != nil {
		return
	}
	file_swm_plugin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_host_proto_rawDesc), len(file_swm_plugin_v1_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swm_plugin_v1_host_proto_goTypes,
		DependencyIndexes: file_swm_plugin_v1_host_proto_depIdxs,
		MessageInfos:      file_swm_plugin_v1_host_proto_msgTypes,
	}.Build()
	File_swm_plugin_v1_host_proto = out.File
	file_swm_plugin_v1_host_proto_goTypes = nil
	file_swm_plugin_v1_host_proto_depIdxs = nil
}
