// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swm/plugin/v1/picker.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PickerInfo is returned by Picker.Info.
type PickerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginInfo    *PluginInfo            `protobuf:"bytes,1,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickerInfo) Reset() {
	*x = PickerInfo{}
	mi := &file_swm_plugin_v1_picker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickerInfo) ProtoMessage() {}

func (x *PickerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_picker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickerInfo.ProtoReflect.Descriptor instead.
func (*PickerInfo) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_picker_proto_rawDescGZIP(), []int{0}
}

func (x *PickerInfo) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

// PickItem is a single candidate streamed from host to picker plugin.
type PickItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Display       string                 `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Preview       string                 `protobuf:"bytes,3,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickItem) Reset() {
	*x = PickItem{}
	mi := &file_swm_plugin_v1_picker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickItem) ProtoMessage() {}

func (x *PickItem) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_picker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickItem.ProtoReflect.Descriptor instead.
func (*PickItem) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_picker_proto_rawDescGZIP(), []int{1}
}

func (x *PickItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PickItem) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *PickItem) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

// PickResult is a selected item streamed from picker plugin back to host.
type PickResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickResult) Reset() {
	*x = PickResult{}
	mi := &file_swm_plugin_v1_picker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickResult) ProtoMessage() {}

func (x *PickResult) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_picker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickResult.ProtoReflect.Descriptor instead.
func (*PickResult) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_picker_proto_rawDescGZIP(), []int{2}
}

func (x *PickResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_swm_plugin_v1_picker_proto protoreflect.FileDescriptor

const file_swm_plugin_v1_picker_proto_rawDesc = "" +
	"\n" +
	"\x1aswm/plugin/v1/picker.proto\x12\rswm.plugin.v1\x1a\x1aswm/plugin/v1/common.proto\"H\n" +
	"\n" +
	"PickerInfo\x12:\n" +
	"\vplugin_info\x18\x01 \x01(\v2\x19.swm.plugin.v1.PluginInfoR\n" +
	"pluginInfo\"P\n" +
	"\bPickItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\x12\x18\n" +
	"\apreview\x18\x03 \x01(\tR\apreview\"\x1e\n" +
	"\n" +
	"PickResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2\x81\x01\n" +
	"\x06Picker\x127\n" +
	"\x04Info\x12\x14.swm.plugin.v1.Empty\x1a\x19.swm.plugin.v1.PickerInfo\x12>\n" +
	"\x04Pick\x12\x17.swm.plugin.v1.PickItem\x1a\x19.swm.plugin.v1.PickResult(\x010\x01B6Z4github.com/kalbasit/swm/proto/swm/plugin/v1;pluginv1b\x06proto3"

var (
	file_swm_plugin_v1_picker_proto_rawDescOnce sync.Once
	file_swm_plugin_v1_picker_proto_rawDescData []byte
)

func file_swm_plugin_v1_picker_proto_rawDescGZIP() []byte {
	file_swm_plugin_v1_picker_proto_rawDescOnce.Do(func() {
		file_swm_plugin_v1_picker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_picker_proto_rawDesc), len(file_swm_plugin_v1_picker_proto_rawDesc)))
	})
	return file_swm_plugin_v1_picker_proto_rawDescData
}

var file_swm_plugin_v1_picker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_swm_plugin_v1_picker_proto_goTypes = []any{
	(*PickerInfo)(nil), // 0: swm.plugin.v1.PickerInfo
	(*PickItem)(nil),   // 1: swm.plugin.v1.PickItem
	(*PickResult)(nil), // 2: swm.plugin.v1.PickResult
	(*PluginInfo)(nil), // 3: swm.plugin.v1.PluginInfo
	(*Empty)(nil),      // 4: swm.plugin.v1.Empty
}
var file_swm_plugin_v1_picker_proto_depIdxs = []int32{
	3, // 0: swm.plugin.v1.PickerInfo.plugin_info:type_name -> swm.plugin.v1.PluginInfo
	4, // 1: swm.plugin.v1.Picker.Info:input_type -> swm.plugin.v1.Empty
	1, // 2: swm.plugin.v1.Picker.Pick:input_type -> swm.plugin.v1.PickItem
	0, // 3: swm.plugin.v1.Picker.Info:output_type -> swm.plugin.v1.PickerInfo
	2, // 4: swm.plugin.v1.Picker.Pick:output_type -> swm.plugin.v1.PickResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_swm_plugin_v1_picker_proto_init() }
func file_swm_plugin_v1_picker_proto_init() {
	if File_swm_plugin_v1_picker_proto != nil {
		return
	}
	file_swm_plugin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_picker_proto_rawDesc), len(file_swm_plugin_v1_picker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swm_plugin_v1_picker_proto_goTypes,
		DependencyIndexes: file_swm_plugin_v1_picker_proto_depIdxs,
		MessageInfos:      file_swm_plugin_v1_picker_proto_msgTypes,
	}.Build()
	File_swm_plugin_v1_picker_proto = out.File
	file_swm_plugin_v1_picker_proto_goTypes = nil
	file_swm_plugin_v1_picker_proto_depIdxs = nil
}
