// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: swm/plugin/v1/picker.proto

package pluginv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Picker_Info_FullMethodName = "/swm.plugin.v1.Picker/Info"
	Picker_Pick_FullMethodName = "/swm.plugin.v1.Picker/Pick"
)

// PickerClient is the client API for Picker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Picker is implemented by interactive-selection plugins (e.g. picker-fzf).
type PickerClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PickerInfo, error)
	// Pick is bidirectional streaming: host sends candidates, plugin returns selections.
	Pick(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PickItem, PickResult], error)
}

type pickerClient struct {
	cc grpc.ClientConnInterface
}

func NewPickerClient(cc grpc.ClientConnInterface) PickerClient {
	return &pickerClient{cc}
}

func (c *pickerClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PickerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickerInfo)
	err := c.cc.Invoke(ctx, Picker_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pickerClient) Pick(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PickItem, PickResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Picker_ServiceDesc.Streams[0], Picker_Pick_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PickItem, PickResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Picker_PickClient = grpc.BidiStreamingClient[PickItem, PickResult]

// PickerServer is the server API for Picker service.
// All implementations should embed UnimplementedPickerServer
// for forward compatibility.
//
// Picker is implemented by interactive-selection plugins (e.g. picker-fzf).
type PickerServer interface {
	Info(context.Context, *Empty) (*PickerInfo, error)
	// Pick is bidirectional streaming: host sends candidates, plugin returns selections.
	Pick(grpc.BidiStreamingServer[PickItem, PickResult]) error
}

// UnimplementedPickerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPickerServer struct{}

func (UnimplementedPickerServer) Info(context.Context, *Empty) (*PickerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}

func (UnimplementedPickerServer) Pick(grpc.BidiStreamingServer[PickItem, PickResult]) error {
	return status.Error(codes.Unimplemented, "method Pick not implemented")
}
func (UnimplementedPickerServer) testEmbeddedByValue() {}

// UnsafePickerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PickerServer will
// result in compilation errors.
type UnsafePickerServer interface {
	mustEmbedUnimplementedPickerServer()
}

func RegisterPickerServer(s grpc.ServiceRegistrar, srv PickerServer) {
	// If the following call panics, it indicates UnimplementedPickerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Picker_ServiceDesc, srv)
}

func _Picker_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PickerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picker_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PickerServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picker_Pick_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PickerServer).Pick(&grpc.GenericServerStream[PickItem, PickResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Picker_PickServer = grpc.BidiStreamingServer[PickItem, PickResult]

// Picker_ServiceDesc is the grpc.ServiceDesc for Picker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Picker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swm.plugin.v1.Picker",
	HandlerType: (*PickerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Picker_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pick",
			Handler:       _Picker_Pick_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "swm/plugin/v1/picker.proto",
}
