// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: swm/plugin/v1/session.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Session_Info_FullMethodName              = "/swm.plugin.v1.Session/Info"
	Session_OpenWorkspace_FullMethodName     = "/swm.plugin.v1.Session/OpenWorkspace"
	Session_CloseWorkspace_FullMethodName    = "/swm.plugin.v1.Session/CloseWorkspace"
	Session_ListWorkspaces_FullMethodName    = "/swm.plugin.v1.Session/ListWorkspaces"
	Session_OpenPaneGroup_FullMethodName     = "/swm.plugin.v1.Session/OpenPaneGroup"
	Session_SwitchTo_FullMethodName          = "/swm.plugin.v1.Session/SwitchTo"
	Session_IsInsideWorkspace_FullMethodName = "/swm.plugin.v1.Session/IsInsideWorkspace"
	Session_CurrentContext_FullMethodName    = "/swm.plugin.v1.Session/CurrentContext"
)

// SessionClient is the client API for Session service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Session is implemented by terminal-multiplexer plugins (e.g. session-tmux).
type SessionClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionInfo, error)
	OpenWorkspace(ctx context.Context, in *OpenWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	CloseWorkspace(ctx context.Context, in *CloseWorkspaceRequest, opts ...grpc.CallOption) (*Empty, error)
	ListWorkspaces(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Workspace], error)
	OpenPaneGroup(ctx context.Context, in *OpenPaneGroupRequest, opts ...grpc.CallOption) (*PaneGroup, error)
	SwitchTo(ctx context.Context, in *SwitchToRequest, opts ...grpc.CallOption) (*SwitchToResponse, error)
	IsInsideWorkspace(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoolValue, error)
	CurrentContext(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CurrentContextResponse, error)
}

type sessionClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionClient(cc grpc.ClientConnInterface) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, Session_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) OpenWorkspace(ctx context.Context, in *OpenWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, Session_OpenWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) CloseWorkspace(ctx context.Context, in *CloseWorkspaceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Session_CloseWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) ListWorkspaces(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Workspace], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Session_ServiceDesc.Streams[0], Session_ListWorkspaces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Workspace]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Session_ListWorkspacesClient = grpc.ServerStreamingClient[Workspace]

func (c *sessionClient) OpenPaneGroup(ctx context.Context, in *OpenPaneGroupRequest, opts ...grpc.CallOption) (*PaneGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaneGroup)
	err := c.cc.Invoke(ctx, Session_OpenPaneGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) SwitchTo(ctx context.Context, in *SwitchToRequest, opts ...grpc.CallOption) (*SwitchToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchToResponse)
	err := c.cc.Invoke(ctx, Session_SwitchTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) IsInsideWorkspace(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolValue)
	err := c.cc.Invoke(ctx, Session_IsInsideWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) CurrentContext(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CurrentContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentContextResponse)
	err := c.cc.Invoke(ctx, Session_CurrentContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServer is the server API for Session service.
// All implementations should embed UnimplementedSessionServer
// for forward compatibility.
//
// Session is implemented by terminal-multiplexer plugins (e.g. session-tmux).
type SessionServer interface {
	Info(context.Context, *Empty) (*SessionInfo, error)
	OpenWorkspace(context.Context, *OpenWorkspaceRequest) (*Workspace, error)
	CloseWorkspace(context.Context, *CloseWorkspaceRequest) (*Empty, error)
	ListWorkspaces(*Empty, grpc.ServerStreamingServer[Workspace]) error
	OpenPaneGroup(context.Context, *OpenPaneGroupRequest) (*PaneGroup, error)
	SwitchTo(context.Context, *SwitchToRequest) (*SwitchToResponse, error)
	IsInsideWorkspace(context.Context, *Empty) (*BoolValue, error)
	CurrentContext(context.Context, *Empty) (*CurrentContextResponse, error)
}

// UnimplementedSessionServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServer struct{}

func (UnimplementedSessionServer) Info(context.Context, *Empty) (*SessionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedSessionServer) OpenWorkspace(context.Context, *OpenWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenWorkspace not implemented")
}
func (UnimplementedSessionServer) CloseWorkspace(context.Context, *CloseWorkspaceRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseWorkspace not implemented")
}
func (UnimplementedSessionServer) ListWorkspaces(*Empty, grpc.ServerStreamingServer[Workspace]) error {
	return status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedSessionServer) OpenPaneGroup(context.Context, *OpenPaneGroupRequest) (*PaneGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenPaneGroup not implemented")
}
func (UnimplementedSessionServer) SwitchTo(context.Context, *SwitchToRequest) (*SwitchToResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchTo not implemented")
}
func (UnimplementedSessionServer) IsInsideWorkspace(context.Context, *Empty) (*BoolValue, error) {
	return nil, status.Error(codes.Unimplemented, "method IsInsideWorkspace not implemented")
}
func (UnimplementedSessionServer) CurrentContext(context.Context, *Empty) (*CurrentContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CurrentContext not implemented")
}
func (UnimplementedSessionServer) testEmbeddedByValue() {}

// UnsafeSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServer will
// result in compilation errors.
type UnsafeSessionServer interface {
	mustEmbedUnimplementedSessionServer()
}

func RegisterSessionServer(s grpc.ServiceRegistrar, srv SessionServer) {
	// If the following call panics, it indicates UnimplementedSessionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Session_ServiceDesc, srv)
}

func _Session_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_OpenWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).OpenWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_OpenWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).OpenWorkspace(ctx, req.(*OpenWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_CloseWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CloseWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_CloseWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CloseWorkspace(ctx, req.(*CloseWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_ListWorkspaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionServer).ListWorkspaces(m, &grpc.GenericServerStream[Empty, Workspace]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Session_ListWorkspacesServer = grpc.ServerStreamingServer[Workspace]

func _Session_OpenPaneGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPaneGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).OpenPaneGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_OpenPaneGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).OpenPaneGroup(ctx, req.(*OpenPaneGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_SwitchTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).SwitchTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_SwitchTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).SwitchTo(ctx, req.(*SwitchToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_IsInsideWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).IsInsideWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_IsInsideWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).IsInsideWorkspace(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_CurrentContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CurrentContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Session_CurrentContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CurrentContext(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Session_ServiceDesc is the grpc.ServiceDesc for Session service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Session_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swm.plugin.v1.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Session_Info_Handler,
		},
		{
			MethodName: "OpenWorkspace",
			Handler:    _Session_OpenWorkspace_Handler,
		},
		{
			MethodName: "CloseWorkspace",
			Handler:    _Session_CloseWorkspace_Handler,
		},
		{
			MethodName: "OpenPaneGroup",
			Handler:    _Session_OpenPaneGroup_Handler,
		},
		{
			MethodName: "SwitchTo",
			Handler:    _Session_SwitchTo_Handler,
		},
		{
			MethodName: "IsInsideWorkspace",
			Handler:    _Session_IsInsideWorkspace_Handler,
		},
		{
			MethodName: "CurrentContext",
			Handler:    _Session_CurrentContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListWorkspaces",
			Handler:       _Session_ListWorkspaces_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swm/plugin/v1/session.proto",
}
