// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swm/plugin/v1/session.proto

package pluginv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionInfo is returned by Session.Info.
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginInfo    *PluginInfo            `protobuf:"bytes,1,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionInfo) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

// Workspace represents an active multiplexer container (e.g. a tmux socket).
type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StoryName     string                 `protobuf:"bytes,2,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *Workspace) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Workspace) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *Workspace) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// PaneGroup represents a project's working environment inside a workspace.
type PaneGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneGroupId   string                 `protobuf:"bytes,1,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     *ProjectID             `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,4,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaneGroup) Reset() {
	*x = PaneGroup{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaneGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaneGroup) ProtoMessage() {}

func (x *PaneGroup) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaneGroup.ProtoReflect.Descriptor instead.
func (*PaneGroup) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *PaneGroup) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

func (x *PaneGroup) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *PaneGroup) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *PaneGroup) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

// CurrentContextResponse describes the session the caller is currently inside.
type CurrentContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StoryName     string                 `protobuf:"bytes,2,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	PaneGroupId   string                 `protobuf:"bytes,3,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	ProjectId     *ProjectID             `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentContextResponse) Reset() {
	*x = CurrentContextResponse{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentContextResponse) ProtoMessage() {}

func (x *CurrentContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentContextResponse.ProtoReflect.Descriptor instead.
func (*CurrentContextResponse) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentContextResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CurrentContextResponse) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *CurrentContextResponse) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

func (x *CurrentContextResponse) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

// OpenWorkspaceRequest asks the plugin to create or attach to a workspace.
type OpenWorkspaceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StoryName string                 `protobuf:"bytes,1,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	// worktree_paths maps project key (host/seg1/.../segN) to absolute path.
	WorktreePaths map[string]string `protobuf:"bytes,2,rep,name=worktree_paths,json=worktreePaths,proto3" json:"worktree_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenWorkspaceRequest) Reset() {
	*x = OpenWorkspaceRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenWorkspaceRequest) ProtoMessage() {}

func (x *OpenWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*OpenWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *OpenWorkspaceRequest) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *OpenWorkspaceRequest) GetWorktreePaths() map[string]string {
	if x != nil {
		return x.WorktreePaths
	}
	return nil
}

// CloseWorkspaceRequest asks the plugin to tear down a workspace.
type CloseWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseWorkspaceRequest) Reset() {
	*x = CloseWorkspaceRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseWorkspaceRequest) ProtoMessage() {}

func (x *CloseWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CloseWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *CloseWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// OpenPaneGroupRequest asks the plugin to open a project pane inside a workspace.
type OpenPaneGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     *ProjectID             `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,3,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPaneGroupRequest) Reset() {
	*x = OpenPaneGroupRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPaneGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPaneGroupRequest) ProtoMessage() {}

func (x *OpenPaneGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPaneGroupRequest.ProtoReflect.Descriptor instead.
func (*OpenPaneGroupRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *OpenPaneGroupRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *OpenPaneGroupRequest) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *OpenPaneGroupRequest) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

// SwitchToRequest asks the plugin to bring a pane group into focus.
type SwitchToRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PaneGroupId   string                 `protobuf:"bytes,2,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchToRequest) Reset() {
	*x = SwitchToRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchToRequest) ProtoMessage() {}

func (x *SwitchToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchToRequest.ProtoReflect.Descriptor instead.
func (*SwitchToRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *SwitchToRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SwitchToRequest) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

var File_swm_plugin_v1_session_proto protoreflect.FileDescriptor

const file_swm_plugin_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1bswm/plugin/v1/session.proto\x12\rswm.plugin.v1\x1a\x1aswm/plugin/v1/common.proto\"I\n" +
	"\vSessionInfo\x12:\n" +
	"\vplugin_info\x18\x01 \x01(\v2\x19.swm.plugin.v1.PluginInfoR\n" +
	"pluginInfo\"e\n" +
	"\tWorkspace\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"story_name\x18\x02 \x01(\tR\tstoryName\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"\xb0\x01\n" +
	"\tPaneGroup\x12\"\n" +
	"\rpane_group_id\x18\x01 \x01(\tR\vpaneGroupId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x127\n" +
	"\n" +
	"project_id\x18\x03 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\x12#\n" +
	"\rworktree_path\x18\x04 \x01(\tR\fworktreePath\"\xb7\x01\n" +
	"\x16CurrentContextResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"story_name\x18\x02 \x01(\tR\tstoryName\x12\"\n" +
	"\rpane_group_id\x18\x03 \x01(\tR\vpaneGroupId\x127\n" +
	"\n" +
	"project_id\x18\x04 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\"\xd6\x01\n" +
	"\x14OpenWorkspaceRequest\x12\x1d\n" +
	"\n" +
	"story_name\x18\x01 \x01(\tR\tstoryName\x12]\n" +
	"\x0eworktree_paths\x18\x02 \x03(\v26.swm.plugin.v1.OpenWorkspaceRequest.WorktreePathsEntryR\rworktreePaths\x1a@\n" +
	"\x12WorktreePathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x15CloseWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\x97\x01\n" +
	"\x14OpenPaneGroupRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x127\n" +
	"\n" +
	"project_id\x18\x02 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\x12#\n" +
	"\rworktree_path\x18\x03 \x01(\tR\fworktreePath\"X\n" +
	"\x0fSwitchToRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\"\n" +
	"\rpane_group_id\x18\x02 \x01(\tR\vpaneGroupId2\xcb\x04\n" +
	"\aSession\x128\n" +
	"\x04Info\x12\x14.swm.plugin.v1.Empty\x1a\x1a.swm.plugin.v1.SessionInfo\x12N\n" +
	"\rOpenWorkspace\x12#.swm.plugin.v1.OpenWorkspaceRequest\x1a\x18.swm.plugin.v1.Workspace\x12L\n" +
	"\x0eCloseWorkspace\x12$.swm.plugin.v1.CloseWorkspaceRequest\x1a\x14.swm.plugin.v1.Empty\x12B\n" +
	"\x0eListWorkspaces\x12\x14.swm.plugin.v1.Empty\x1a\x18.swm.plugin.v1.Workspace0\x01\x12N\n" +
	"\rOpenPaneGroup\x12#.swm.plugin.v1.OpenPaneGroupRequest\x1a\x18.swm.plugin.v1.PaneGroup\x12@\n" +
	"\bSwitchTo\x12\x1e.swm.plugin.v1.SwitchToRequest\x1a\x14.swm.plugin.v1.Empty\x12C\n" +
	"\x11IsInsideWorkspace\x12\x14.swm.plugin.v1.Empty\x1a\x18.swm.plugin.v1.BoolValue\x12M\n" +
	"\x0eCurrentContext\x12\x14.swm.plugin.v1.Empty\x1a%.swm.plugin.v1.CurrentContextResponseB6Z4github.com/kalbasit/swm/proto/swm/plugin/v1;pluginv1b\x06proto3"

var (
	file_swm_plugin_v1_session_proto_rawDescOnce sync.Once
	file_swm_plugin_v1_session_proto_rawDescData []byte
)

func file_swm_plugin_v1_session_proto_rawDescGZIP() []byte {
	file_swm_plugin_v1_session_proto_rawDescOnce.Do(func() {
		file_swm_plugin_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_session_proto_rawDesc), len(file_swm_plugin_v1_session_proto_rawDesc)))
	})
	return file_swm_plugin_v1_session_proto_rawDescData
}

var (
	file_swm_plugin_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
	file_swm_plugin_v1_session_proto_goTypes  = []any{
		(*SessionInfo)(nil),            // 0: swm.plugin.v1.SessionInfo
		(*Workspace)(nil),              // 1: swm.plugin.v1.Workspace
		(*PaneGroup)(nil),              // 2: swm.plugin.v1.PaneGroup
		(*CurrentContextResponse)(nil), // 3: swm.plugin.v1.CurrentContextResponse
		(*OpenWorkspaceRequest)(nil),   // 4: swm.plugin.v1.OpenWorkspaceRequest
		(*CloseWorkspaceRequest)(nil),  // 5: swm.plugin.v1.CloseWorkspaceRequest
		(*OpenPaneGroupRequest)(nil),   // 6: swm.plugin.v1.OpenPaneGroupRequest
		(*SwitchToRequest)(nil),        // 7: swm.plugin.v1.SwitchToRequest
		nil,                            // 8: swm.plugin.v1.OpenWorkspaceRequest.WorktreePathsEntry
		(*PluginInfo)(nil),             // 9: swm.plugin.v1.PluginInfo
		(*ProjectID)(nil),              // 10: swm.plugin.v1.ProjectID
		(*Empty)(nil),                  // 11: swm.plugin.v1.Empty
		(*BoolValue)(nil),              // 12: swm.plugin.v1.BoolValue
	}
)

var file_swm_plugin_v1_session_proto_depIdxs = []int32{
	9,  // 0: swm.plugin.v1.SessionInfo.plugin_info:type_name -> swm.plugin.v1.PluginInfo
	10, // 1: swm.plugin.v1.PaneGroup.project_id:type_name -> swm.plugin.v1.ProjectID
	10, // 2: swm.plugin.v1.CurrentContextResponse.project_id:type_name -> swm.plugin.v1.ProjectID
	8,  // 3: swm.plugin.v1.OpenWorkspaceRequest.worktree_paths:type_name -> swm.plugin.v1.OpenWorkspaceRequest.WorktreePathsEntry
	10, // 4: swm.plugin.v1.OpenPaneGroupRequest.project_id:type_name -> swm.plugin.v1.ProjectID
	11, // 5: swm.plugin.v1.Session.Info:input_type -> swm.plugin.v1.Empty
	4,  // 6: swm.plugin.v1.Session.OpenWorkspace:input_type -> swm.plugin.v1.OpenWorkspaceRequest
	5,  // 7: swm.plugin.v1.Session.CloseWorkspace:input_type -> swm.plugin.v1.CloseWorkspaceRequest
	11, // 8: swm.plugin.v1.Session.ListWorkspaces:input_type -> swm.plugin.v1.Empty
	6,  // 9: swm.plugin.v1.Session.OpenPaneGroup:input_type -> swm.plugin.v1.OpenPaneGroupRequest
	7,  // 10: swm.plugin.v1.Session.SwitchTo:input_type -> swm.plugin.v1.SwitchToRequest
	11, // 11: swm.plugin.v1.Session.IsInsideWorkspace:input_type -> swm.plugin.v1.Empty
	11, // 12: swm.plugin.v1.Session.CurrentContext:input_type -> swm.plugin.v1.Empty
	0,  // 13: swm.plugin.v1.Session.Info:output_type -> swm.plugin.v1.SessionInfo
	1,  // 14: swm.plugin.v1.Session.OpenWorkspace:output_type -> swm.plugin.v1.Workspace
	11, // 15: swm.plugin.v1.Session.CloseWorkspace:output_type -> swm.plugin.v1.Empty
	1,  // 16: swm.plugin.v1.Session.ListWorkspaces:output_type -> swm.plugin.v1.Workspace
	2,  // 17: swm.plugin.v1.Session.OpenPaneGroup:output_type -> swm.plugin.v1.PaneGroup
	11, // 18: swm.plugin.v1.Session.SwitchTo:output_type -> swm.plugin.v1.Empty
	12, // 19: swm.plugin.v1.Session.IsInsideWorkspace:output_type -> swm.plugin.v1.BoolValue
	3,  // 20: swm.plugin.v1.Session.CurrentContext:output_type -> swm.plugin.v1.CurrentContextResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_swm_plugin_v1_session_proto_init() }
func file_swm_plugin_v1_session_proto_init() {
	if File_swm_plugin_v1_session_proto != nil {
		return
	}
	file_swm_plugin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_session_proto_rawDesc), len(file_swm_plugin_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swm_plugin_v1_session_proto_goTypes,
		DependencyIndexes: file_swm_plugin_v1_session_proto_depIdxs,
		MessageInfos:      file_swm_plugin_v1_session_proto_msgTypes,
	}.Build()
	File_swm_plugin_v1_session_proto = out.File
	file_swm_plugin_v1_session_proto_goTypes = nil
	file_swm_plugin_v1_session_proto_depIdxs = nil
}
