// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: swm/plugin/v1/session.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionInfo is returned by Session.Info.
type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginInfo    *PluginInfo            `protobuf:"bytes,1,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionInfo) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

// Workspace represents an active multiplexer container (e.g. a tmux socket).
type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StoryName     string                 `protobuf:"bytes,2,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *Workspace) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Workspace) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *Workspace) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// PaneGroup represents a project's working environment inside a workspace.
type PaneGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaneGroupId   string                 `protobuf:"bytes,1,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     *ProjectID             `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,4,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaneGroup) Reset() {
	*x = PaneGroup{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaneGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaneGroup) ProtoMessage() {}

func (x *PaneGroup) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaneGroup.ProtoReflect.Descriptor instead.
func (*PaneGroup) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *PaneGroup) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

func (x *PaneGroup) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *PaneGroup) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *PaneGroup) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

// CurrentContextResponse describes the session the caller is currently inside.
type CurrentContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StoryName     string                 `protobuf:"bytes,2,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	PaneGroupId   string                 `protobuf:"bytes,3,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	ProjectId     *ProjectID             `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentContextResponse) Reset() {
	*x = CurrentContextResponse{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentContextResponse) ProtoMessage() {}

func (x *CurrentContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentContextResponse.ProtoReflect.Descriptor instead.
func (*CurrentContextResponse) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentContextResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CurrentContextResponse) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *CurrentContextResponse) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

func (x *CurrentContextResponse) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

// OpenWorkspaceRequest asks the plugin to create or attach to a workspace.
type OpenWorkspaceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StoryName string                 `protobuf:"bytes,1,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	// worktree_paths maps project key (host/seg1/.../segN) to absolute path.
	WorktreePaths map[string]string `protobuf:"bytes,2,rep,name=worktree_paths,json=worktreePaths,proto3" json:"worktree_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenWorkspaceRequest) Reset() {
	*x = OpenWorkspaceRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenWorkspaceRequest) ProtoMessage() {}

func (x *OpenWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*OpenWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *OpenWorkspaceRequest) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *OpenWorkspaceRequest) GetWorktreePaths() map[string]string {
	if x != nil {
		return x.WorktreePaths
	}
	return nil
}

// CloseWorkspaceRequest asks the plugin to tear down a workspace.
type CloseWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseWorkspaceRequest) Reset() {
	*x = CloseWorkspaceRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseWorkspaceRequest) ProtoMessage() {}

func (x *CloseWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CloseWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *CloseWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// OpenPaneGroupRequest asks the plugin to open a project pane inside a workspace.
type OpenPaneGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     *ProjectID             `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,3,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPaneGroupRequest) Reset() {
	*x = OpenPaneGroupRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPaneGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPaneGroupRequest) ProtoMessage() {}

func (x *OpenPaneGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPaneGroupRequest.ProtoReflect.Descriptor instead.
func (*OpenPaneGroupRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *OpenPaneGroupRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *OpenPaneGroupRequest) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *OpenPaneGroupRequest) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

// SwitchToRequest asks the plugin to bring a pane group into focus.
type SwitchToRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PaneGroupId string                 `protobuf:"bytes,2,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	// Optional: if non-empty, the plugin SHALL close the originating pane after
	// switching. close_origin_workspace_id identifies the source workspace and
	// close_origin_pane_id is the multiplexer-specific pane reference (e.g.
	// $TMUX_PANE for session-tmux).
	CloseOriginWorkspaceId string `protobuf:"bytes,3,opt,name=close_origin_workspace_id,json=closeOriginWorkspaceId,proto3" json:"close_origin_workspace_id,omitempty"`
	CloseOriginPaneId      string `protobuf:"bytes,4,opt,name=close_origin_pane_id,json=closeOriginPaneId,proto3" json:"close_origin_pane_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SwitchToRequest) Reset() {
	*x = SwitchToRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchToRequest) ProtoMessage() {}

func (x *SwitchToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchToRequest.ProtoReflect.Descriptor instead.
func (*SwitchToRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *SwitchToRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SwitchToRequest) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

func (x *SwitchToRequest) GetCloseOriginWorkspaceId() string {
	if x != nil {
		return x.CloseOriginWorkspaceId
	}
	return ""
}

func (x *SwitchToRequest) GetCloseOriginPaneId() string {
	if x != nil {
		return x.CloseOriginPaneId
	}
	return ""
}

// SwitchToResponse is returned by Session.SwitchTo.
// When exec_argv is non-empty the host MUST exec the command to hand the
// terminal over (e.g. tmux attach-session when not already inside tmux).
type SwitchToResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecArgv      []string               `protobuf:"bytes,1,rep,name=exec_argv,json=execArgv,proto3" json:"exec_argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchToResponse) Reset() {
	*x = SwitchToResponse{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchToResponse) ProtoMessage() {}

func (x *SwitchToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchToResponse.ProtoReflect.Descriptor instead.
func (*SwitchToResponse) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *SwitchToResponse) GetExecArgv() []string {
	if x != nil {
		return x.ExecArgv
	}
	return nil
}

// Pane represents a single addressable pane inside a pane group. It is the
// place a program runs; what that program is, is the caller's concern and not
// something swm models.
type Pane struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pane_id is an opaque handle minted by the plugin. Its format is
	// provider-specific ("%4" for session-tmux). Callers MUST pass it back
	// verbatim and MUST NOT parse it, construct it, or derive meaning from it.
	//
	// This is not a new kind of value on this service:
	// SwitchToRequest.close_origin_pane_id already carries a
	// multiplexer-specific pane reference across the same boundary.
	//
	// A pane_id is meaningful only within the workspace that produced it, which
	// is why every request carrying one also carries a workspace_id.
	PaneId      string `protobuf:"bytes,1,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	PaneGroupId string `protobuf:"bytes,2,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	WorkspaceId string `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The fields below are descriptive, not identity. They are reported by the
	// provider on a best-effort basis: a provider that cannot supply one leaves
	// it at its zero value. They exist so ListPanes can answer "what is running
	// here" without the caller inspecting the multiplexer itself.
	Title          string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	CurrentCommand string `protobuf:"bytes,5,opt,name=current_command,json=currentCommand,proto3" json:"current_command,omitempty"`
	CurrentPath    string `protobuf:"bytes,6,opt,name=current_path,json=currentPath,proto3" json:"current_path,omitempty"`
	// focused is true when the multiplexer reports that this pane is where an
	// attached client's keystrokes currently land — i.e. a human typing right
	// now would type into this pane. SendText refuses such a pane by default;
	// see SendTextRequest.allow_focused.
	Focused       bool `protobuf:"varint,7,opt,name=focused,proto3" json:"focused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pane) Reset() {
	*x = Pane{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pane) ProtoMessage() {}

func (x *Pane) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pane.ProtoReflect.Descriptor instead.
func (*Pane) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *Pane) GetPaneId() string {
	if x != nil {
		return x.PaneId
	}
	return ""
}

func (x *Pane) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

func (x *Pane) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Pane) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Pane) GetCurrentCommand() string {
	if x != nil {
		return x.CurrentCommand
	}
	return ""
}

func (x *Pane) GetCurrentPath() string {
	if x != nil {
		return x.CurrentPath
	}
	return ""
}

func (x *Pane) GetFocused() bool {
	if x != nil {
		return x.Focused
	}
	return false
}

// OpenPaneRequest asks the plugin to start a program in a new pane.
type OpenPaneRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PaneGroupId string                 `protobuf:"bytes,2,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	// argv is the program and its arguments, already split. An element
	// containing spaces or shell metacharacters is passed through intact and is
	// never re-split. Empty argv starts the provider's default shell.
	Argv []string `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	// cwd, when non-empty, is the pane's starting directory.
	Cwd string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// env entries are set in the new pane's environment.
	Env           map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPaneRequest) Reset() {
	*x = OpenPaneRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPaneRequest) ProtoMessage() {}

func (x *OpenPaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPaneRequest.ProtoReflect.Descriptor instead.
func (*OpenPaneRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *OpenPaneRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *OpenPaneRequest) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

func (x *OpenPaneRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *OpenPaneRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *OpenPaneRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// ListPanesRequest asks the plugin to enumerate panes. Both filters are
// optional: an empty workspace_id enumerates every live workspace, and an
// empty pane_group_id enumerates every pane group within those workspaces.
type ListPanesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PaneGroupId   string                 `protobuf:"bytes,2,opt,name=pane_group_id,json=paneGroupId,proto3" json:"pane_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPanesRequest) Reset() {
	*x = ListPanesRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPanesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPanesRequest) ProtoMessage() {}

func (x *ListPanesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPanesRequest.ProtoReflect.Descriptor instead.
func (*ListPanesRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *ListPanesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListPanesRequest) GetPaneGroupId() string {
	if x != nil {
		return x.PaneGroupId
	}
	return ""
}

// SendTextRequest asks the plugin to deliver text to a pane.
//
// HAZARD: the text arrives exactly as if a human had typed it. Whatever the
// pane is currently displaying will consume it — including a confirmation
// prompt a human is in the middle of answering. Delivery into a pane a person
// is using can therefore answer a question on their behalf.
type SendTextRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PaneId      string                 `protobuf:"bytes,2,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	// text is delivered literally. No part of it is interpreted as a key name,
	// so "Enter" arrives as five characters and not as the Enter key.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// submit appends the provider's submit key (Enter) after the text, as a
	// separate delivery. Empty text with submit set delivers only that key,
	// which is how a caller inserts a gap between text and submission: send the
	// text, then send the submit key with a delay. Empty text without submit is
	// INVALID_ARGUMENT — there is nothing to deliver.
	Submit bool `protobuf:"varint,4,opt,name=submit,proto3" json:"submit,omitempty"`
	// delay_ms, when positive, is observed BEFORE delivering. This is the same
	// mitigation session-tmux's layout config exposes as pane_cmd_delay: a
	// program that has just started may not have installed its input handler
	// yet, and keystrokes arriving before it does are lost.
	DelayMs int32 `protobuf:"varint,5,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	// allow_focused overrides the plugin's refusal to deliver into a pane it
	// reports as focused (see Pane.focused). Plugins SHALL refuse a focused pane
	// with FAILED_PRECONDITION unless this is set. The check is inherently racy
	// — a human can focus the pane immediately after it passes — so it is a
	// guard against the common accident, not a guarantee. A caller that sets
	// this owns the consequences.
	AllowFocused  bool `protobuf:"varint,6,opt,name=allow_focused,json=allowFocused,proto3" json:"allow_focused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *SendTextRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SendTextRequest) GetPaneId() string {
	if x != nil {
		return x.PaneId
	}
	return ""
}

func (x *SendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendTextRequest) GetSubmit() bool {
	if x != nil {
		return x.Submit
	}
	return false
}

func (x *SendTextRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *SendTextRequest) GetAllowFocused() bool {
	if x != nil {
		return x.AllowFocused
	}
	return false
}

// ClosePaneRequest asks the plugin to terminate a pane. Closing a pane that no
// longer exists is not an error; cleaning up after a program that already
// exited is the normal case.
type ClosePaneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PaneId        string                 `protobuf:"bytes,2,opt,name=pane_id,json=paneId,proto3" json:"pane_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePaneRequest) Reset() {
	*x = ClosePaneRequest{}
	mi := &file_swm_plugin_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePaneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePaneRequest) ProtoMessage() {}

func (x *ClosePaneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePaneRequest.ProtoReflect.Descriptor instead.
func (*ClosePaneRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *ClosePaneRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ClosePaneRequest) GetPaneId() string {
	if x != nil {
		return x.PaneId
	}
	return ""
}

var File_swm_plugin_v1_session_proto protoreflect.FileDescriptor

const file_swm_plugin_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1bswm/plugin/v1/session.proto\x12\rswm.plugin.v1\x1a\x1aswm/plugin/v1/common.proto\"I\n" +
	"\vSessionInfo\x12:\n" +
	"\vplugin_info\x18\x01 \x01(\v2\x19.swm.plugin.v1.PluginInfoR\n" +
	"pluginInfo\"e\n" +
	"\tWorkspace\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"story_name\x18\x02 \x01(\tR\tstoryName\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"\xb0\x01\n" +
	"\tPaneGroup\x12\"\n" +
	"\rpane_group_id\x18\x01 \x01(\tR\vpaneGroupId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x127\n" +
	"\n" +
	"project_id\x18\x03 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\x12#\n" +
	"\rworktree_path\x18\x04 \x01(\tR\fworktreePath\"\xb7\x01\n" +
	"\x16CurrentContextResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"story_name\x18\x02 \x01(\tR\tstoryName\x12\"\n" +
	"\rpane_group_id\x18\x03 \x01(\tR\vpaneGroupId\x127\n" +
	"\n" +
	"project_id\x18\x04 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\"\xd6\x01\n" +
	"\x14OpenWorkspaceRequest\x12\x1d\n" +
	"\n" +
	"story_name\x18\x01 \x01(\tR\tstoryName\x12]\n" +
	"\x0eworktree_paths\x18\x02 \x03(\v26.swm.plugin.v1.OpenWorkspaceRequest.WorktreePathsEntryR\rworktreePaths\x1a@\n" +
	"\x12WorktreePathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x15CloseWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\x97\x01\n" +
	"\x14OpenPaneGroupRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x127\n" +
	"\n" +
	"project_id\x18\x02 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\x12#\n" +
	"\rworktree_path\x18\x03 \x01(\tR\fworktreePath\"\xc4\x01\n" +
	"\x0fSwitchToRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\"\n" +
	"\rpane_group_id\x18\x02 \x01(\tR\vpaneGroupId\x129\n" +
	"\x19close_origin_workspace_id\x18\x03 \x01(\tR\x16closeOriginWorkspaceId\x12/\n" +
	"\x14close_origin_pane_id\x18\x04 \x01(\tR\x11closeOriginPaneId\"/\n" +
	"\x10SwitchToResponse\x12\x1b\n" +
	"\texec_argv\x18\x01 \x03(\tR\bexecArgv\"\xe2\x01\n" +
	"\x04Pane\x12\x17\n" +
	"\apane_id\x18\x01 \x01(\tR\x06paneId\x12\"\n" +
	"\rpane_group_id\x18\x02 \x01(\tR\vpaneGroupId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12'\n" +
	"\x0fcurrent_command\x18\x05 \x01(\tR\x0ecurrentCommand\x12!\n" +
	"\fcurrent_path\x18\x06 \x01(\tR\vcurrentPath\x12\x18\n" +
	"\afocused\x18\a \x01(\bR\afocused\"\xf1\x01\n" +
	"\x0fOpenPaneRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\"\n" +
	"\rpane_group_id\x18\x02 \x01(\tR\vpaneGroupId\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x129\n" +
	"\x03env\x18\x05 \x03(\v2'.swm.plugin.v1.OpenPaneRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x10ListPanesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\"\n" +
	"\rpane_group_id\x18\x02 \x01(\tR\vpaneGroupId\"\xb9\x01\n" +
	"\x0fSendTextRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\apane_id\x18\x02 \x01(\tR\x06paneId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x16\n" +
	"\x06submit\x18\x04 \x01(\bR\x06submit\x12\x19\n" +
	"\bdelay_ms\x18\x05 \x01(\x05R\adelayMs\x12#\n" +
	"\rallow_focused\x18\x06 \x01(\bR\fallowFocused\"N\n" +
	"\x10ClosePaneRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\apane_id\x18\x02 \x01(\tR\x06paneId2\xe2\x06\n" +
	"\aSession\x128\n" +
	"\x04Info\x12\x14.swm.plugin.v1.Empty\x1a\x1a.swm.plugin.v1.SessionInfo\x12N\n" +
	"\rOpenWorkspace\x12#.swm.plugin.v1.OpenWorkspaceRequest\x1a\x18.swm.plugin.v1.Workspace\x12L\n" +
	"\x0eCloseWorkspace\x12$.swm.plugin.v1.CloseWorkspaceRequest\x1a\x14.swm.plugin.v1.Empty\x12B\n" +
	"\x0eListWorkspaces\x12\x14.swm.plugin.v1.Empty\x1a\x18.swm.plugin.v1.Workspace0\x01\x12N\n" +
	"\rOpenPaneGroup\x12#.swm.plugin.v1.OpenPaneGroupRequest\x1a\x18.swm.plugin.v1.PaneGroup\x12K\n" +
	"\bSwitchTo\x12\x1e.swm.plugin.v1.SwitchToRequest\x1a\x1f.swm.plugin.v1.SwitchToResponse\x12C\n" +
	"\x11IsInsideWorkspace\x12\x14.swm.plugin.v1.Empty\x1a\x18.swm.plugin.v1.BoolValue\x12M\n" +
	"\x0eCurrentContext\x12\x14.swm.plugin.v1.Empty\x1a%.swm.plugin.v1.CurrentContextResponse\x12?\n" +
	"\bOpenPane\x12\x1e.swm.plugin.v1.OpenPaneRequest\x1a\x13.swm.plugin.v1.Pane\x12C\n" +
	"\tListPanes\x12\x1f.swm.plugin.v1.ListPanesRequest\x1a\x13.swm.plugin.v1.Pane0\x01\x12@\n" +
	"\bSendText\x12\x1e.swm.plugin.v1.SendTextRequest\x1a\x14.swm.plugin.v1.Empty\x12B\n" +
	"\tClosePane\x12\x1f.swm.plugin.v1.ClosePaneRequest\x1a\x14.swm.plugin.v1.EmptyB6Z4github.com/kalbasit/swm/proto/swm/plugin/v1;pluginv1b\x06proto3"

var (
	file_swm_plugin_v1_session_proto_rawDescOnce sync.Once
	file_swm_plugin_v1_session_proto_rawDescData []byte
)

func file_swm_plugin_v1_session_proto_rawDescGZIP() []byte {
	file_swm_plugin_v1_session_proto_rawDescOnce.Do(func() {
		file_swm_plugin_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_session_proto_rawDesc), len(file_swm_plugin_v1_session_proto_rawDesc)))
	})
	return file_swm_plugin_v1_session_proto_rawDescData
}

var file_swm_plugin_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_swm_plugin_v1_session_proto_goTypes = []any{
	(*SessionInfo)(nil),            // 0: swm.plugin.v1.SessionInfo
	(*Workspace)(nil),              // 1: swm.plugin.v1.Workspace
	(*PaneGroup)(nil),              // 2: swm.plugin.v1.PaneGroup
	(*CurrentContextResponse)(nil), // 3: swm.plugin.v1.CurrentContextResponse
	(*OpenWorkspaceRequest)(nil),   // 4: swm.plugin.v1.OpenWorkspaceRequest
	(*CloseWorkspaceRequest)(nil),  // 5: swm.plugin.v1.CloseWorkspaceRequest
	(*OpenPaneGroupRequest)(nil),   // 6: swm.plugin.v1.OpenPaneGroupRequest
	(*SwitchToRequest)(nil),        // 7: swm.plugin.v1.SwitchToRequest
	(*SwitchToResponse)(nil),       // 8: swm.plugin.v1.SwitchToResponse
	(*Pane)(nil),                   // 9: swm.plugin.v1.Pane
	(*OpenPaneRequest)(nil),        // 10: swm.plugin.v1.OpenPaneRequest
	(*ListPanesRequest)(nil),       // 11: swm.plugin.v1.ListPanesRequest
	(*SendTextRequest)(nil),        // 12: swm.plugin.v1.SendTextRequest
	(*ClosePaneRequest)(nil),       // 13: swm.plugin.v1.ClosePaneRequest
	nil,                            // 14: swm.plugin.v1.OpenWorkspaceRequest.WorktreePathsEntry
	nil,                            // 15: swm.plugin.v1.OpenPaneRequest.EnvEntry
	(*PluginInfo)(nil),             // 16: swm.plugin.v1.PluginInfo
	(*ProjectID)(nil),              // 17: swm.plugin.v1.ProjectID
	(*Empty)(nil),                  // 18: swm.plugin.v1.Empty
	(*BoolValue)(nil),              // 19: swm.plugin.v1.BoolValue
}
var file_swm_plugin_v1_session_proto_depIdxs = []int32{
	16, // 0: swm.plugin.v1.SessionInfo.plugin_info:type_name -> swm.plugin.v1.PluginInfo
	17, // 1: swm.plugin.v1.PaneGroup.project_id:type_name -> swm.plugin.v1.ProjectID
	17, // 2: swm.plugin.v1.CurrentContextResponse.project_id:type_name -> swm.plugin.v1.ProjectID
	14, // 3: swm.plugin.v1.OpenWorkspaceRequest.worktree_paths:type_name -> swm.plugin.v1.OpenWorkspaceRequest.WorktreePathsEntry
	17, // 4: swm.plugin.v1.OpenPaneGroupRequest.project_id:type_name -> swm.plugin.v1.ProjectID
	15, // 5: swm.plugin.v1.OpenPaneRequest.env:type_name -> swm.plugin.v1.OpenPaneRequest.EnvEntry
	18, // 6: swm.plugin.v1.Session.Info:input_type -> swm.plugin.v1.Empty
	4,  // 7: swm.plugin.v1.Session.OpenWorkspace:input_type -> swm.plugin.v1.OpenWorkspaceRequest
	5,  // 8: swm.plugin.v1.Session.CloseWorkspace:input_type -> swm.plugin.v1.CloseWorkspaceRequest
	18, // 9: swm.plugin.v1.Session.ListWorkspaces:input_type -> swm.plugin.v1.Empty
	6,  // 10: swm.plugin.v1.Session.OpenPaneGroup:input_type -> swm.plugin.v1.OpenPaneGroupRequest
	7,  // 11: swm.plugin.v1.Session.SwitchTo:input_type -> swm.plugin.v1.SwitchToRequest
	18, // 12: swm.plugin.v1.Session.IsInsideWorkspace:input_type -> swm.plugin.v1.Empty
	18, // 13: swm.plugin.v1.Session.CurrentContext:input_type -> swm.plugin.v1.Empty
	10, // 14: swm.plugin.v1.Session.OpenPane:input_type -> swm.plugin.v1.OpenPaneRequest
	11, // 15: swm.plugin.v1.Session.ListPanes:input_type -> swm.plugin.v1.ListPanesRequest
	12, // 16: swm.plugin.v1.Session.SendText:input_type -> swm.plugin.v1.SendTextRequest
	13, // 17: swm.plugin.v1.Session.ClosePane:input_type -> swm.plugin.v1.ClosePaneRequest
	0,  // 18: swm.plugin.v1.Session.Info:output_type -> swm.plugin.v1.SessionInfo
	1,  // 19: swm.plugin.v1.Session.OpenWorkspace:output_type -> swm.plugin.v1.Workspace
	18, // 20: swm.plugin.v1.Session.CloseWorkspace:output_type -> swm.plugin.v1.Empty
	1,  // 21: swm.plugin.v1.Session.ListWorkspaces:output_type -> swm.plugin.v1.Workspace
	2,  // 22: swm.plugin.v1.Session.OpenPaneGroup:output_type -> swm.plugin.v1.PaneGroup
	8,  // 23: swm.plugin.v1.Session.SwitchTo:output_type -> swm.plugin.v1.SwitchToResponse
	19, // 24: swm.plugin.v1.Session.IsInsideWorkspace:output_type -> swm.plugin.v1.BoolValue
	3,  // 25: swm.plugin.v1.Session.CurrentContext:output_type -> swm.plugin.v1.CurrentContextResponse
	9,  // 26: swm.plugin.v1.Session.OpenPane:output_type -> swm.plugin.v1.Pane
	9,  // 27: swm.plugin.v1.Session.ListPanes:output_type -> swm.plugin.v1.Pane
	18, // 28: swm.plugin.v1.Session.SendText:output_type -> swm.plugin.v1.Empty
	18, // 29: swm.plugin.v1.Session.ClosePane:output_type -> swm.plugin.v1.Empty
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_swm_plugin_v1_session_proto_init() }
func file_swm_plugin_v1_session_proto_init() {
	if File_swm_plugin_v1_session_proto != nil {
		return
	}
	file_swm_plugin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_session_proto_rawDesc), len(file_swm_plugin_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swm_plugin_v1_session_proto_goTypes,
		DependencyIndexes: file_swm_plugin_v1_session_proto_depIdxs,
		MessageInfos:      file_swm_plugin_v1_session_proto_msgTypes,
	}.Build()
	File_swm_plugin_v1_session_proto = out.File
	file_swm_plugin_v1_session_proto_goTypes = nil
	file_swm_plugin_v1_session_proto_depIdxs = nil
}
