// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: swm/plugin/v1/vcs.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VCSInfo is returned by VCS.Info.
type VCSInfo struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PluginInfo *PluginInfo            `protobuf:"bytes,1,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	// project_markers are filenames whose presence marks a directory as a project
	// root (e.g. [".git"] for git, [".jj"] for jujutsu).
	ProjectMarkers []string `protobuf:"bytes,2,rep,name=project_markers,json=projectMarkers,proto3" json:"project_markers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VCSInfo) Reset() {
	*x = VCSInfo{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VCSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCSInfo) ProtoMessage() {}

func (x *VCSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCSInfo.ProtoReflect.Descriptor instead.
func (*VCSInfo) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{0}
}

func (x *VCSInfo) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

func (x *VCSInfo) GetProjectMarkers() []string {
	if x != nil {
		return x.ProjectMarkers
	}
	return nil
}

// CloneRequest asks the plugin to clone a remote URL.
type CloneRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{1}
}

func (x *CloneRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CloneRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

// CloneResponse returns the resolved project identity after cloning.
type CloneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *ProjectID             `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{2}
}

func (x *CloneResponse) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

// ParseRemoteURLRequest asks the plugin to parse a URL into a ProjectID.
type ParseRemoteURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRemoteURLRequest) Reset() {
	*x = ParseRemoteURLRequest{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRemoteURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRemoteURLRequest) ProtoMessage() {}

func (x *ParseRemoteURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRemoteURLRequest.ProtoReflect.Descriptor instead.
func (*ParseRemoteURLRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{3}
}

func (x *ParseRemoteURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// CreateWorktreeRequest asks the plugin to create a per-story worktree.
type CreateWorktreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *ProjectID             `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	StoryName     string                 `protobuf:"bytes,2,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	BranchName    string                 `protobuf:"bytes,3,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	RepoPath      string                 `protobuf:"bytes,4,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,5,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorktreeRequest) Reset() {
	*x = CreateWorktreeRequest{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorktreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorktreeRequest) ProtoMessage() {}

func (x *CreateWorktreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorktreeRequest.ProtoReflect.Descriptor instead.
func (*CreateWorktreeRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorktreeRequest) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *CreateWorktreeRequest) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *CreateWorktreeRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *CreateWorktreeRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *CreateWorktreeRequest) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

// RemoveWorktreeRequest asks the plugin to remove a story's worktree.
type RemoveWorktreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *ProjectID             `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	StoryName     string                 `protobuf:"bytes,2,opt,name=story_name,json=storyName,proto3" json:"story_name,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,3,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorktreeRequest) Reset() {
	*x = RemoveWorktreeRequest{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorktreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorktreeRequest) ProtoMessage() {}

func (x *RemoveWorktreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorktreeRequest.ProtoReflect.Descriptor instead.
func (*RemoveWorktreeRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveWorktreeRequest) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *RemoveWorktreeRequest) GetStoryName() string {
	if x != nil {
		return x.StoryName
	}
	return ""
}

func (x *RemoveWorktreeRequest) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

// DetectAtPathRequest asks the plugin to identify the project at a path.
type DetectAtPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectAtPathRequest) Reset() {
	*x = DetectAtPathRequest{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectAtPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectAtPathRequest) ProtoMessage() {}

func (x *DetectAtPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectAtPathRequest.ProtoReflect.Descriptor instead.
func (*DetectAtPathRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{6}
}

func (x *DetectAtPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ListBranchesRequest asks for all branches in a repository.
type ListBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *ProjectID             `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RepoPath      string                 `protobuf:"bytes,2,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesRequest) Reset() {
	*x = ListBranchesRequest{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesRequest) ProtoMessage() {}

func (x *ListBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListBranchesRequest) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{7}
}

func (x *ListBranchesRequest) GetProjectId() *ProjectID {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *ListBranchesRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

// Branch describes a single VCS branch.
type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsRemote      bool                   `protobuf:"varint,2,opt,name=is_remote,json=isRemote,proto3" json:"is_remote,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,3,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_swm_plugin_v1_vcs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_swm_plugin_v1_vcs_proto_rawDescGZIP(), []int{8}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetIsRemote() bool {
	if x != nil {
		return x.IsRemote
	}
	return false
}

func (x *Branch) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

var File_swm_plugin_v1_vcs_proto protoreflect.FileDescriptor

const file_swm_plugin_v1_vcs_proto_rawDesc = "" +
	"\n" +
	"\x17swm/plugin/v1/vcs.proto\x12\rswm.plugin.v1\x1a\x1aswm/plugin/v1/common.proto\"n\n" +
	"\aVCSInfo\x12:\n" +
	"\vplugin_info\x18\x01 \x01(\v2\x19.swm.plugin.v1.PluginInfoR\n" +
	"pluginInfo\x12'\n" +
	"\x0fproject_markers\x18\x02 \x03(\tR\x0eprojectMarkers\"K\n" +
	"\fCloneRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\"H\n" +
	"\rCloneResponse\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\")\n" +
	"\x15ParseRemoteURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xd2\x01\n" +
	"\x15CreateWorktreeRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\x12\x1d\n" +
	"\n" +
	"story_name\x18\x02 \x01(\tR\tstoryName\x12\x1f\n" +
	"\vbranch_name\x18\x03 \x01(\tR\n" +
	"branchName\x12\x1b\n" +
	"\trepo_path\x18\x04 \x01(\tR\brepoPath\x12#\n" +
	"\rworktree_path\x18\x05 \x01(\tR\fworktreePath\"\x94\x01\n" +
	"\x15RemoveWorktreeRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\x12\x1d\n" +
	"\n" +
	"story_name\x18\x02 \x01(\tR\tstoryName\x12#\n" +
	"\rworktree_path\x18\x03 \x01(\tR\fworktreePath\")\n" +
	"\x13DetectAtPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"k\n" +
	"\x13ListBranchesRequest\x127\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x18.swm.plugin.v1.ProjectIDR\tprojectId\x12\x1b\n" +
	"\trepo_path\x18\x02 \x01(\tR\brepoPath\"X\n" +
	"\x06Branch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_remote\x18\x02 \x01(\bR\bisRemote\x12\x1d\n" +
	"\n" +
	"is_current\x18\x03 \x01(\bR\tisCurrent2\x8f\x04\n" +
	"\x03VCS\x124\n" +
	"\x04Info\x12\x14.swm.plugin.v1.Empty\x1a\x16.swm.plugin.v1.VCSInfo\x12B\n" +
	"\x05Clone\x12\x1b.swm.plugin.v1.CloneRequest\x1a\x1c.swm.plugin.v1.CloneResponse\x12P\n" +
	"\x0eParseRemoteURL\x12$.swm.plugin.v1.ParseRemoteURLRequest\x1a\x18.swm.plugin.v1.ProjectID\x12L\n" +
	"\x0eCreateWorktree\x12$.swm.plugin.v1.CreateWorktreeRequest\x1a\x14.swm.plugin.v1.Empty\x12L\n" +
	"\x0eRemoveWorktree\x12$.swm.plugin.v1.RemoveWorktreeRequest\x1a\x14.swm.plugin.v1.Empty\x12S\n" +
	"\x13DetectProjectAtPath\x12\".swm.plugin.v1.DetectAtPathRequest\x1a\x18.swm.plugin.v1.ProjectID\x12K\n" +
	"\fListBranches\x12\".swm.plugin.v1.ListBranchesRequest\x1a\x15.swm.plugin.v1.Branch0\x01B6Z4github.com/kalbasit/swm/proto/swm/plugin/v1;pluginv1b\x06proto3"

var (
	file_swm_plugin_v1_vcs_proto_rawDescOnce sync.Once
	file_swm_plugin_v1_vcs_proto_rawDescData []byte
)

func file_swm_plugin_v1_vcs_proto_rawDescGZIP() []byte {
	file_swm_plugin_v1_vcs_proto_rawDescOnce.Do(func() {
		file_swm_plugin_v1_vcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_vcs_proto_rawDesc), len(file_swm_plugin_v1_vcs_proto_rawDesc)))
	})
	return file_swm_plugin_v1_vcs_proto_rawDescData
}

var file_swm_plugin_v1_vcs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_swm_plugin_v1_vcs_proto_goTypes = []any{
	(*VCSInfo)(nil),               // 0: swm.plugin.v1.VCSInfo
	(*CloneRequest)(nil),          // 1: swm.plugin.v1.CloneRequest
	(*CloneResponse)(nil),         // 2: swm.plugin.v1.CloneResponse
	(*ParseRemoteURLRequest)(nil), // 3: swm.plugin.v1.ParseRemoteURLRequest
	(*CreateWorktreeRequest)(nil), // 4: swm.plugin.v1.CreateWorktreeRequest
	(*RemoveWorktreeRequest)(nil), // 5: swm.plugin.v1.RemoveWorktreeRequest
	(*DetectAtPathRequest)(nil),   // 6: swm.plugin.v1.DetectAtPathRequest
	(*ListBranchesRequest)(nil),   // 7: swm.plugin.v1.ListBranchesRequest
	(*Branch)(nil),                // 8: swm.plugin.v1.Branch
	(*PluginInfo)(nil),            // 9: swm.plugin.v1.PluginInfo
	(*ProjectID)(nil),             // 10: swm.plugin.v1.ProjectID
	(*Empty)(nil),                 // 11: swm.plugin.v1.Empty
}
var file_swm_plugin_v1_vcs_proto_depIdxs = []int32{
	9,  // 0: swm.plugin.v1.VCSInfo.plugin_info:type_name -> swm.plugin.v1.PluginInfo
	10, // 1: swm.plugin.v1.CloneResponse.project_id:type_name -> swm.plugin.v1.ProjectID
	10, // 2: swm.plugin.v1.CreateWorktreeRequest.project_id:type_name -> swm.plugin.v1.ProjectID
	10, // 3: swm.plugin.v1.RemoveWorktreeRequest.project_id:type_name -> swm.plugin.v1.ProjectID
	10, // 4: swm.plugin.v1.ListBranchesRequest.project_id:type_name -> swm.plugin.v1.ProjectID
	11, // 5: swm.plugin.v1.VCS.Info:input_type -> swm.plugin.v1.Empty
	1,  // 6: swm.plugin.v1.VCS.Clone:input_type -> swm.plugin.v1.CloneRequest
	3,  // 7: swm.plugin.v1.VCS.ParseRemoteURL:input_type -> swm.plugin.v1.ParseRemoteURLRequest
	4,  // 8: swm.plugin.v1.VCS.CreateWorktree:input_type -> swm.plugin.v1.CreateWorktreeRequest
	5,  // 9: swm.plugin.v1.VCS.RemoveWorktree:input_type -> swm.plugin.v1.RemoveWorktreeRequest
	6,  // 10: swm.plugin.v1.VCS.DetectProjectAtPath:input_type -> swm.plugin.v1.DetectAtPathRequest
	7,  // 11: swm.plugin.v1.VCS.ListBranches:input_type -> swm.plugin.v1.ListBranchesRequest
	0,  // 12: swm.plugin.v1.VCS.Info:output_type -> swm.plugin.v1.VCSInfo
	2,  // 13: swm.plugin.v1.VCS.Clone:output_type -> swm.plugin.v1.CloneResponse
	10, // 14: swm.plugin.v1.VCS.ParseRemoteURL:output_type -> swm.plugin.v1.ProjectID
	11, // 15: swm.plugin.v1.VCS.CreateWorktree:output_type -> swm.plugin.v1.Empty
	11, // 16: swm.plugin.v1.VCS.RemoveWorktree:output_type -> swm.plugin.v1.Empty
	10, // 17: swm.plugin.v1.VCS.DetectProjectAtPath:output_type -> swm.plugin.v1.ProjectID
	8,  // 18: swm.plugin.v1.VCS.ListBranches:output_type -> swm.plugin.v1.Branch
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_swm_plugin_v1_vcs_proto_init() }
func file_swm_plugin_v1_vcs_proto_init() {
	if File_swm_plugin_v1_vcs_proto != nil {
		return
	}
	file_swm_plugin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swm_plugin_v1_vcs_proto_rawDesc), len(file_swm_plugin_v1_vcs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swm_plugin_v1_vcs_proto_goTypes,
		DependencyIndexes: file_swm_plugin_v1_vcs_proto_depIdxs,
		MessageInfos:      file_swm_plugin_v1_vcs_proto_msgTypes,
	}.Build()
	File_swm_plugin_v1_vcs_proto = out.File
	file_swm_plugin_v1_vcs_proto_goTypes = nil
	file_swm_plugin_v1_vcs_proto_depIdxs = nil
}
