// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: swm/plugin/v1/vcs.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VCS_Info_FullMethodName                = "/swm.plugin.v1.VCS/Info"
	VCS_Clone_FullMethodName               = "/swm.plugin.v1.VCS/Clone"
	VCS_ParseRemoteURL_FullMethodName      = "/swm.plugin.v1.VCS/ParseRemoteURL"
	VCS_CreateWorktree_FullMethodName      = "/swm.plugin.v1.VCS/CreateWorktree"
	VCS_RemoveWorktree_FullMethodName      = "/swm.plugin.v1.VCS/RemoveWorktree"
	VCS_DetectProjectAtPath_FullMethodName = "/swm.plugin.v1.VCS/DetectProjectAtPath"
	VCS_ListBranches_FullMethodName        = "/swm.plugin.v1.VCS/ListBranches"
)

// VCSClient is the client API for VCS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VCS is implemented by version-control plugins (e.g. vcs-git).
type VCSClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VCSInfo, error)
	Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*CloneResponse, error)
	ParseRemoteURL(ctx context.Context, in *ParseRemoteURLRequest, opts ...grpc.CallOption) (*ProjectID, error)
	CreateWorktree(ctx context.Context, in *CreateWorktreeRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveWorktree(ctx context.Context, in *RemoveWorktreeRequest, opts ...grpc.CallOption) (*Empty, error)
	DetectProjectAtPath(ctx context.Context, in *DetectAtPathRequest, opts ...grpc.CallOption) (*ProjectID, error)
	ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Branch], error)
}

type vCSClient struct {
	cc grpc.ClientConnInterface
}

func NewVCSClient(cc grpc.ClientConnInterface) VCSClient {
	return &vCSClient{cc}
}

func (c *vCSClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VCSInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VCSInfo)
	err := c.cc.Invoke(ctx, VCS_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSClient) Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*CloneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneResponse)
	err := c.cc.Invoke(ctx, VCS_Clone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSClient) ParseRemoteURL(ctx context.Context, in *ParseRemoteURLRequest, opts ...grpc.CallOption) (*ProjectID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectID)
	err := c.cc.Invoke(ctx, VCS_ParseRemoteURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSClient) CreateWorktree(ctx context.Context, in *CreateWorktreeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VCS_CreateWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSClient) RemoveWorktree(ctx context.Context, in *RemoveWorktreeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VCS_RemoveWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSClient) DetectProjectAtPath(ctx context.Context, in *DetectAtPathRequest, opts ...grpc.CallOption) (*ProjectID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectID)
	err := c.cc.Invoke(ctx, VCS_DetectProjectAtPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSClient) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Branch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VCS_ServiceDesc.Streams[0], VCS_ListBranches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListBranchesRequest, Branch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VCS_ListBranchesClient = grpc.ServerStreamingClient[Branch]

// VCSServer is the server API for VCS service.
// All implementations should embed UnimplementedVCSServer
// for forward compatibility.
//
// VCS is implemented by version-control plugins (e.g. vcs-git).
type VCSServer interface {
	Info(context.Context, *Empty) (*VCSInfo, error)
	Clone(context.Context, *CloneRequest) (*CloneResponse, error)
	ParseRemoteURL(context.Context, *ParseRemoteURLRequest) (*ProjectID, error)
	CreateWorktree(context.Context, *CreateWorktreeRequest) (*Empty, error)
	RemoveWorktree(context.Context, *RemoveWorktreeRequest) (*Empty, error)
	DetectProjectAtPath(context.Context, *DetectAtPathRequest) (*ProjectID, error)
	ListBranches(*ListBranchesRequest, grpc.ServerStreamingServer[Branch]) error
}

// UnimplementedVCSServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVCSServer struct{}

func (UnimplementedVCSServer) Info(context.Context, *Empty) (*VCSInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedVCSServer) Clone(context.Context, *CloneRequest) (*CloneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedVCSServer) ParseRemoteURL(context.Context, *ParseRemoteURLRequest) (*ProjectID, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseRemoteURL not implemented")
}
func (UnimplementedVCSServer) CreateWorktree(context.Context, *CreateWorktreeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorktree not implemented")
}
func (UnimplementedVCSServer) RemoveWorktree(context.Context, *RemoveWorktreeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorktree not implemented")
}
func (UnimplementedVCSServer) DetectProjectAtPath(context.Context, *DetectAtPathRequest) (*ProjectID, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectProjectAtPath not implemented")
}
func (UnimplementedVCSServer) ListBranches(*ListBranchesRequest, grpc.ServerStreamingServer[Branch]) error {
	return status.Error(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedVCSServer) testEmbeddedByValue() {}

// UnsafeVCSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VCSServer will
// result in compilation errors.
type UnsafeVCSServer interface {
	mustEmbedUnimplementedVCSServer()
}

func RegisterVCSServer(s grpc.ServiceRegistrar, srv VCSServer) {
	// If the following call panics, it indicates UnimplementedVCSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VCS_ServiceDesc, srv)
}

func _VCS_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCS_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCS_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCS_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServer).Clone(ctx, req.(*CloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCS_ParseRemoteURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRemoteURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServer).ParseRemoteURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCS_ParseRemoteURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServer).ParseRemoteURL(ctx, req.(*ParseRemoteURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCS_CreateWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServer).CreateWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCS_CreateWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServer).CreateWorktree(ctx, req.(*CreateWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCS_RemoveWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorktreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServer).RemoveWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCS_RemoveWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServer).RemoveWorktree(ctx, req.(*RemoveWorktreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCS_DetectProjectAtPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectAtPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSServer).DetectProjectAtPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCS_DetectProjectAtPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSServer).DetectProjectAtPath(ctx, req.(*DetectAtPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCS_ListBranches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBranchesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VCSServer).ListBranches(m, &grpc.GenericServerStream[ListBranchesRequest, Branch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VCS_ListBranchesServer = grpc.ServerStreamingServer[Branch]

// VCS_ServiceDesc is the grpc.ServiceDesc for VCS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VCS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swm.plugin.v1.VCS",
	HandlerType: (*VCSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _VCS_Info_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _VCS_Clone_Handler,
		},
		{
			MethodName: "ParseRemoteURL",
			Handler:    _VCS_ParseRemoteURL_Handler,
		},
		{
			MethodName: "CreateWorktree",
			Handler:    _VCS_CreateWorktree_Handler,
		},
		{
			MethodName: "RemoveWorktree",
			Handler:    _VCS_RemoveWorktree_Handler,
		},
		{
			MethodName: "DetectProjectAtPath",
			Handler:    _VCS_DetectProjectAtPath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBranches",
			Handler:       _VCS_ListBranches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swm/plugin/v1/vcs.proto",
}
